# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autokeyinForm.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_autokeyinForm(object):
    def setupUi(self, autokeyinForm):
        autokeyinForm.setObjectName("autokeyinForm")
        autokeyinForm.resize(407, 484)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        autokeyinForm.setFont(font)
        autokeyinForm.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.layoutWidget = QtWidgets.QWidget(autokeyinForm)
        self.layoutWidget.setGeometry(QtCore.QRect(4, 3, 398, 481))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.Cate_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.Cate_comboBox.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Cate_comboBox.setFont(font)
        self.Cate_comboBox.setObjectName("Cate_comboBox")
        self.horizontalLayout.addWidget(self.Cate_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.antukeytree = QtWidgets.QTreeWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK TC Regular")
        font.setPointSize(12)
        self.antukeytree.setFont(font)
        self.antukeytree.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.antukeytree.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.antukeytree.setObjectName("antukeytree")
        self.antukeytree.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.antukeytree)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_nodule = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.add_nodule.setFont(font)
        self.add_nodule.setObjectName("add_nodule")
        self.horizontalLayout_2.addWidget(self.add_nodule)
        self.list_nodules = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.list_nodules.setFont(font)
        self.list_nodules.setObjectName("list_nodules")
        self.horizontalLayout_2.addWidget(self.list_nodules)
        self.simple = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.simple.setFont(font)
        self.simple.setObjectName("simple")
        self.horizontalLayout_2.addWidget(self.simple)
        self.antokey_Button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.antokey_Button.setFont(font)
        self.antokey_Button.setObjectName("antokey_Button")
        self.horizontalLayout_2.addWidget(self.antokey_Button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(autokeyinForm)
        QtCore.QMetaObject.connectSlotsByName(autokeyinForm)

    def retranslateUi(self, autokeyinForm):
        _translate = QtCore.QCoreApplication.translate
        autokeyinForm.setWindowTitle(_translate("autokeyinForm", "autokeyinForm"))
        self.radioButton.setText(_translate("autokeyinForm", "cm"))
        self.radioButton_2.setText(_translate("autokeyinForm", "mm"))
        self.antukeytree.headerItem().setText(1, _translate("autokeyinForm", "number"))
        self.add_nodule.setText(_translate("autokeyinForm", "add nodule"))
        self.list_nodules.setText(_translate("autokeyinForm", "List Nodules"))
        self.simple.setText(_translate("autokeyinForm", "Simple form"))
        self.antokey_Button.setText(_translate("autokeyinForm", "Send"))

