# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checklist_old.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(640, 700))
        Form.setMaximumSize(QtCore.QSize(640, 700))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK TC Regular")
        font.setPointSize(12)
        Form.setFont(font)
        Form.setFocusPolicy(QtCore.Qt.StrongFocus)
        Form.setAutoFillBackground(True)
        self.clear_Button = QtWidgets.QPushButton(Form)
        self.clear_Button.setGeometry(QtCore.QRect(470, 660, 75, 32))
        self.clear_Button.setObjectName("clear_Button")
        self.test_Button = QtWidgets.QPushButton(Form)
        self.test_Button.setGeometry(QtCore.QRect(9, 659, 75, 32))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK TC Light")
        self.test_Button.setFont(font)
        self.test_Button.setObjectName("test_Button")
        self.take_Button = QtWidgets.QPushButton(Form)
        self.take_Button.setGeometry(QtCore.QRect(328, 659, 75, 32))
        self.take_Button.setObjectName("take_Button")
        self.minput_Button = QtWidgets.QPushButton(Form)
        self.minput_Button.setGeometry(QtCore.QRect(169, 659, 75, 32))
        self.minput_Button.setObjectName("minput_Button")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(4, 1, 630, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.brain = QtWidgets.QWidget()
        self.brain.setObjectName("brain")
        self.gridLayout = QtWidgets.QGridLayout(self.brain)
        self.gridLayout.setObjectName("gridLayout")
        self.combo_brain = QtWidgets.QComboBox(self.brain)
        self.combo_brain.setObjectName("combo_brain")
        self.combo_brain.addItem("")
        self.combo_brain.addItem("")
        self.combo_brain.addItem("")
        self.combo_brain.addItem("")
        self.gridLayout.addWidget(self.combo_brain, 0, 0, 1, 1)
        self.tabWidget.addTab(self.brain, "")
        self.head_neck = QtWidgets.QWidget()
        self.head_neck.setObjectName("head_neck")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.head_neck)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.combo_hn = QtWidgets.QComboBox(self.head_neck)
        self.combo_hn.setObjectName("combo_hn")
        self.combo_hn.addItem("")
        self.combo_hn.addItem("")
        self.combo_hn.addItem("")
        self.combo_hn.addItem("")
        self.verticalLayout_3.addWidget(self.combo_hn)
        self.tabWidget.addTab(self.head_neck, "")
        self.lung = QtWidgets.QWidget()
        self.lung.setObjectName("lung")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.lung)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.combo_lung = QtWidgets.QComboBox(self.lung)
        self.combo_lung.setObjectName("combo_lung")
        self.combo_lung.addItem("")
        self.combo_lung.addItem("")
        self.combo_lung.addItem("")
        self.combo_lung.addItem("")
        self.verticalLayout_4.addWidget(self.combo_lung)
        self.tabWidget.addTab(self.lung, "")
        self.med = QtWidgets.QWidget()
        self.med.setObjectName("med")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.med)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.combo_med = QtWidgets.QComboBox(self.med)
        self.combo_med.setObjectName("combo_med")
        self.combo_med.addItem("")
        self.combo_med.addItem("")
        self.combo_med.addItem("")
        self.combo_med.addItem("")
        self.verticalLayout_5.addWidget(self.combo_med)
        self.tabWidget.addTab(self.med, "")
        self.abd = QtWidgets.QWidget()
        self.abd.setObjectName("abd")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.abd)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.combo_abd = QtWidgets.QComboBox(self.abd)
        self.combo_abd.setObjectName("combo_abd")
        self.combo_abd.addItem("")
        self.combo_abd.addItem("")
        self.combo_abd.addItem("")
        self.combo_abd.addItem("")
        self.verticalLayout_6.addWidget(self.combo_abd)
        self.tabWidget.addTab(self.abd, "")
        self.pelvic = QtWidgets.QWidget()
        self.pelvic.setObjectName("pelvic")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pelvic)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.combo_pelvic = QtWidgets.QComboBox(self.pelvic)
        self.combo_pelvic.setObjectName("combo_pelvic")
        self.combo_pelvic.addItem("")
        self.combo_pelvic.addItem("")
        self.combo_pelvic.addItem("")
        self.combo_pelvic.addItem("")
        self.verticalLayout_7.addWidget(self.combo_pelvic)
        self.tabWidget.addTab(self.pelvic, "")
        self.others = QtWidgets.QWidget()
        self.others.setObjectName("others")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.others)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.combo_others = QtWidgets.QComboBox(self.others)
        self.combo_others.setObjectName("combo_others")
        self.combo_others.addItem("")
        self.combo_others.addItem("")
        self.combo_others.addItem("")
        self.combo_others.addItem("")
        self.verticalLayout_8.addWidget(self.combo_others)
        self.tabWidget.addTab(self.others, "")
        self.whole = QtWidgets.QWidget()
        self.whole.setObjectName("whole")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.whole)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.combo_whole = QtWidgets.QComboBox(self.whole)
        self.combo_whole.setObjectName("combo_whole")
        self.combo_whole.addItem("")
        self.combo_whole.addItem("")
        self.combo_whole.addItem("")
        self.combo_whole.addItem("")
        self.verticalLayout_9.addWidget(self.combo_whole)
        self.tabWidget.addTab(self.whole, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.treeWidget = QtWidgets.QTreeWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.treeWidget.setFont(font)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.tabWidget_2 = QtWidgets.QTabWidget(Form)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 290, 621, 361))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.clear_Button.setText(_translate("Form", "Clear"))
        self.test_Button.setText(_translate("Form", "Test"))
        self.take_Button.setText(_translate("Form", "TakeOut"))
        self.minput_Button.setText(_translate("Form", "MInput"))
        self.combo_brain.setCurrentText(_translate("Form", "Unchecked"))
        self.combo_brain.setItemText(0, _translate("Form", "Unchecked"))
        self.combo_brain.setItemText(1, _translate("Form", "Normal"))
        self.combo_brain.setItemText(2, _translate("Form", "Checked"))
        self.combo_brain.setItemText(3, _translate("Form", "Abnormal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.brain), _translate("Form", "*Brain"))
        self.combo_hn.setCurrentText(_translate("Form", "Unchecked"))
        self.combo_hn.setItemText(0, _translate("Form", "Unchecked"))
        self.combo_hn.setItemText(1, _translate("Form", "Normal"))
        self.combo_hn.setItemText(2, _translate("Form", "Checked"))
        self.combo_hn.setItemText(3, _translate("Form", "Abnormal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.head_neck), _translate("Form", "*H and N"))
        self.combo_lung.setCurrentText(_translate("Form", "Unchecked"))
        self.combo_lung.setItemText(0, _translate("Form", "Unchecked"))
        self.combo_lung.setItemText(1, _translate("Form", "Normal"))
        self.combo_lung.setItemText(2, _translate("Form", "Checked"))
        self.combo_lung.setItemText(3, _translate("Form", "Abnormal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lung), _translate("Form", "*Lung"))
        self.combo_med.setCurrentText(_translate("Form", "Unchecked"))
        self.combo_med.setItemText(0, _translate("Form", "Unchecked"))
        self.combo_med.setItemText(1, _translate("Form", "Normal"))
        self.combo_med.setItemText(2, _translate("Form", "Checked"))
        self.combo_med.setItemText(3, _translate("Form", "Abnormal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.med), _translate("Form", "*Med"))
        self.combo_abd.setCurrentText(_translate("Form", "Unchecked"))
        self.combo_abd.setItemText(0, _translate("Form", "Unchecked"))
        self.combo_abd.setItemText(1, _translate("Form", "Normal"))
        self.combo_abd.setItemText(2, _translate("Form", "Checked"))
        self.combo_abd.setItemText(3, _translate("Form", "Abnormal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.abd), _translate("Form", "*Abd"))
        self.combo_pelvic.setCurrentText(_translate("Form", "Unchecked"))
        self.combo_pelvic.setItemText(0, _translate("Form", "Unchecked"))
        self.combo_pelvic.setItemText(1, _translate("Form", "Normal"))
        self.combo_pelvic.setItemText(2, _translate("Form", "Checked"))
        self.combo_pelvic.setItemText(3, _translate("Form", "Abnormal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pelvic), _translate("Form", "*Pelvic"))
        self.combo_others.setCurrentText(_translate("Form", "Unchecked"))
        self.combo_others.setItemText(0, _translate("Form", "Unchecked"))
        self.combo_others.setItemText(1, _translate("Form", "Normal"))
        self.combo_others.setItemText(2, _translate("Form", "Checked"))
        self.combo_others.setItemText(3, _translate("Form", "Abnormal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.others), _translate("Form", "*Others"))
        self.combo_whole.setCurrentText(_translate("Form", "Unchecked"))
        self.combo_whole.setItemText(0, _translate("Form", "Unchecked"))
        self.combo_whole.setItemText(1, _translate("Form", "Normal"))
        self.combo_whole.setItemText(2, _translate("Form", "Checked"))
        self.combo_whole.setItemText(3, _translate("Form", "Abnormal"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.whole), _translate("Form", "*Whole"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("Form", "Tab 2"))

