# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checklist.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(640, 900))
        Form.setMaximumSize(QtCore.QSize(640, 900))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        Form.setFont(font)
        Form.setFocusPolicy(QtCore.Qt.StrongFocus)
        Form.setAutoFillBackground(True)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(15, 865, 611, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Not_Ask_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.Not_Ask_checkBox.setObjectName("Not_Ask_checkBox")
        self.horizontalLayout.addWidget(self.Not_Ask_checkBox)
        self.line_number_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.line_number_checkBox.setChecked(True)
        self.line_number_checkBox.setObjectName("line_number_checkBox")
        self.horizontalLayout.addWidget(self.line_number_checkBox)
        self.Conculsion_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.Conculsion_Button.setObjectName("Conculsion_Button")
        self.horizontalLayout.addWidget(self.Conculsion_Button)
        self.take_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.take_Button.setObjectName("take_Button")
        self.horizontalLayout.addWidget(self.take_Button)
        self.clear_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.clear_Button.setObjectName("clear_Button")
        self.horizontalLayout.addWidget(self.clear_Button)
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(9, 38, 620, 34))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.seetingBox = QtWidgets.QComboBox(self.layoutWidget_2)
        self.seetingBox.setObjectName("seetingBox")
        self.horizontalLayout_2.addWidget(self.seetingBox)
        self.minput_Button_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.minput_Button_2.setObjectName("minput_Button_2")
        self.horizontalLayout_2.addWidget(self.minput_Button_2)
        self.note_Button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.note_Button.setObjectName("note_Button")
        self.horizontalLayout_2.addWidget(self.note_Button)
        self.save_Button = QtWidgets.QPushButton(self.layoutWidget_2)
        self.save_Button.setObjectName("save_Button")
        self.horizontalLayout_2.addWidget(self.save_Button)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(4, 73, 631, 320))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.tabWidget)
        self.treeWidget = QtWidgets.QTreeWidget(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.treeWidget.setFont(font)
        self.treeWidget.setDragEnabled(False)
        self.treeWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "shortcut")
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.treeWidget.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.treeWidget.headerItem().setFont(1, font)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.treeWidget.headerItem().setFont(2, font)
        self.verticalLayout.addWidget(self.treeWidget)
        self.report_tab = QtWidgets.QTabWidget(Form)
        self.report_tab.setGeometry(QtCore.QRect(6, 396, 630, 470))
        self.report_tab.setObjectName("report_tab")
        self.History = QtWidgets.QWidget()
        self.History.setObjectName("History")
        self.report_tab.addTab(self.History, "")
        self.Findings = QtWidgets.QWidget()
        self.Findings.setObjectName("Findings")
        self.report_tab.addTab(self.Findings, "")
        self.Conclusions = QtWidgets.QWidget()
        self.Conclusions.setObjectName("Conclusions")
        self.report_tab.addTab(self.Conclusions, "")
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(8, 5, 621, 29))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pid_lab = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.pid_lab.setFont(font)
        self.pid_lab.setObjectName("pid_lab")
        self.horizontalLayout_3.addWidget(self.pid_lab)
        self.patient_id = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.patient_id.setFont(font)
        self.patient_id.setObjectName("patient_id")
        self.horizontalLayout_3.addWidget(self.patient_id)
        self.addButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_3.addWidget(self.addButton)
        self.patient_comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.patient_comboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.patient_comboBox.setAcceptDrops(False)
        self.patient_comboBox.setObjectName("patient_comboBox")
        self.horizontalLayout_3.addWidget(self.patient_comboBox)
        self.cleanButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.cleanButton.setObjectName("cleanButton")
        self.horizontalLayout_3.addWidget(self.cleanButton)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget_2.raise_()
        self.report_tab.raise_()

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(-1)
        self.report_tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Not_Ask_checkBox.setText(_translate("Form", "Do Not Ask"))
        self.line_number_checkBox.setText(_translate("Form", "Line number"))
        self.Conculsion_Button.setText(_translate("Form", "Conculsion"))
        self.take_Button.setText(_translate("Form", "TakeOut"))
        self.clear_Button.setText(_translate("Form", "Clear"))
        self.minput_Button_2.setText(_translate("Form", "MInput"))
        self.note_Button.setText(_translate("Form", "Note"))
        self.save_Button.setText(_translate("Form", "Save"))
        self.treeWidget.headerItem().setText(1, _translate("Form", "main"))
        self.treeWidget.headerItem().setText(2, _translate("Form", "index"))
        self.treeWidget.headerItem().setText(3, _translate("Form", "multirows"))
        self.report_tab.setTabText(self.report_tab.indexOf(self.History), _translate("Form", "History"))
        self.report_tab.setTabText(self.report_tab.indexOf(self.Findings), _translate("Form", "Findings"))
        self.report_tab.setTabText(self.report_tab.indexOf(self.Conclusions), _translate("Form", "Conclusions"))
        self.pid_lab.setText(_translate("Form", "Patient ID"))
        self.addButton.setText(_translate("Form", "Add"))
        self.cleanButton.setText(_translate("Form", "Clean"))

