# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Edit_Dialog(object):
    def setupUi(self, Edit_Dialog):
        Edit_Dialog.setObjectName("Edit_Dialog")
        Edit_Dialog.resize(583, 506)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        Edit_Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Edit_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Edit_Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.category_Box = QtWidgets.QComboBox(Edit_Dialog)
        self.category_Box.setObjectName("category_Box")
        self.gridLayout.addWidget(self.category_Box, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(Edit_Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.shortcut_Edit = QtWidgets.QLineEdit(Edit_Dialog)
        self.shortcut_Edit.setObjectName("shortcut_Edit")
        self.gridLayout.addWidget(self.shortcut_Edit, 1, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(Edit_Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 2)
        self.description_Edit = QtWidgets.QLineEdit(Edit_Dialog)
        self.description_Edit.setObjectName("description_Edit")
        self.gridLayout.addWidget(self.description_Edit, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Edit_Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.tamplate_TextEdit = QtWidgets.QPlainTextEdit(Edit_Dialog)
        self.tamplate_TextEdit.setObjectName("tamplate_TextEdit")
        self.gridLayout.addWidget(self.tamplate_TextEdit, 3, 1, 7, 2)
        self.pushButton = QtWidgets.QPushButton(Edit_Dialog)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Edit_Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 5, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(Edit_Dialog)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 6, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Edit_Dialog)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 7, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(Edit_Dialog)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 8, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(Edit_Dialog)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 9, 0, 1, 1)
        self.check_active = QtWidgets.QCheckBox(Edit_Dialog)
        self.check_active.setObjectName("check_active")
        self.gridLayout.addWidget(self.check_active, 10, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Edit_Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 10, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Edit_Dialog)
        self.buttonBox.accepted.connect(Edit_Dialog.accept)
        self.buttonBox.rejected.connect(Edit_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Edit_Dialog)

    def retranslateUi(self, Edit_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Edit_Dialog.setWindowTitle(_translate("Edit_Dialog", "Dialog"))
        self.label.setText(_translate("Edit_Dialog", "Category"))
        self.label_2.setText(_translate("Edit_Dialog", "Shortcut"))
        self.label_4.setText(_translate("Edit_Dialog", "Description"))
        self.label_3.setText(_translate("Edit_Dialog", "Tamplate"))
        self.pushButton.setText(_translate("Edit_Dialog", "Horizontal"))
        self.pushButton_2.setText(_translate("Edit_Dialog", "Vertical"))
        self.pushButton_3.setText(_translate("Edit_Dialog", "Multiple"))
        self.pushButton_4.setText(_translate("Edit_Dialog", "Grid "))
        self.pushButton_5.setText(_translate("Edit_Dialog", "Conclusion"))
        self.pushButton_6.setText(_translate("Edit_Dialog", "PushButton"))
        self.check_active.setText(_translate("Edit_Dialog", "active"))

