# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lung_nodule.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Lung_nodule_Dialog(object):
    def setupUi(self, Lung_nodule_Dialog):
        Lung_nodule_Dialog.setObjectName("Lung_nodule_Dialog")
        Lung_nodule_Dialog.resize(700, 300)
        Lung_nodule_Dialog.setMinimumSize(QtCore.QSize(700, 300))
        Lung_nodule_Dialog.setMaximumSize(QtCore.QSize(700, 300))
        self.label = QtWidgets.QLabel(Lung_nodule_Dialog)
        self.label.setGeometry(QtCore.QRect(5, 5, 251, 261))
        self.label.setMinimumSize(QtCore.QSize(230, 0))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("anatomy-of-lungs.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.treeWidget = QtWidgets.QTreeWidget(Lung_nodule_Dialog)
        self.treeWidget.setGeometry(QtCore.QRect(385, 4, 311, 260))
        self.treeWidget.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.treeWidget.setFont(font)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.RML = QtWidgets.QRadioButton(Lung_nodule_Dialog)
        self.RML.setGeometry(QtCore.QRect(80, 150, 51, 51))
        self.RML.setText("")
        self.RML.setObjectName("RML")
        self.RLL = QtWidgets.QRadioButton(Lung_nodule_Dialog)
        self.RLL.setGeometry(QtCore.QRect(35, 189, 41, 41))
        self.RLL.setText("")
        self.RLL.setObjectName("RLL")
        self.LUL = QtWidgets.QRadioButton(Lung_nodule_Dialog)
        self.LUL.setGeometry(QtCore.QRect(150, 30, 61, 141))
        self.LUL.setText("")
        self.LUL.setObjectName("LUL")
        self.LLL = QtWidgets.QRadioButton(Lung_nodule_Dialog)
        self.LLL.setGeometry(QtCore.QRect(201, 176, 31, 71))
        self.LLL.setText("")
        self.LLL.setObjectName("LLL")
        self.layoutWidget = QtWidgets.QWidget(Lung_nodule_Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(263, 9, 121, 250))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 7, 0, 1, 2)
        self.position = QtWidgets.QLineEdit(self.layoutWidget)
        self.position.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.position.setFont(font)
        self.position.setObjectName("position")
        self.gridLayout.addWidget(self.position, 6, 1, 1, 2)
        self.lesionBox = QtWidgets.QComboBox(self.layoutWidget)
        self.lesionBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.lesionBox.setFont(font)
        self.lesionBox.setObjectName("lesionBox")
        self.lesionBox.addItem("")
        self.lesionBox.addItem("")
        self.lesionBox.addItem("")
        self.lesionBox.addItem("")
        self.lesionBox.addItem("")
        self.gridLayout.addWidget(self.lesionBox, 3, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.uptake = QtWidgets.QComboBox(self.layoutWidget)
        self.uptake.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.uptake.setFont(font)
        self.uptake.setObjectName("uptake")
        self.uptake.addItem("")
        self.uptake.addItem("")
        self.uptake.addItem("")
        self.uptake.addItem("")
        self.uptake.addItem("")
        self.gridLayout.addWidget(self.uptake, 4, 0, 1, 3)
        self.maxSUV = QtWidgets.QLineEdit(self.layoutWidget)
        self.maxSUV.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.maxSUV.setFont(font)
        self.maxSUV.setObjectName("maxSUV")
        self.gridLayout.addWidget(self.maxSUV, 7, 2, 1, 1)
        self.size = QtWidgets.QLineEdit(self.layoutWidget)
        self.size.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.size.setFont(font)
        self.size.setObjectName("size")
        self.gridLayout.addWidget(self.size, 5, 1, 1, 2)
        self.segmentBox = QtWidgets.QComboBox(self.layoutWidget)
        self.segmentBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.segmentBox.setFont(font)
        self.segmentBox.setObjectName("segmentBox")
        self.gridLayout.addWidget(self.segmentBox, 1, 0, 1, 3)
        self.numberBox = QtWidgets.QComboBox(self.layoutWidget)
        self.numberBox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.numberBox.setFont(font)
        self.numberBox.setObjectName("numberBox")
        self.numberBox.addItem("")
        self.numberBox.addItem("")
        self.numberBox.addItem("")
        self.numberBox.addItem("")
        self.numberBox.addItem("")
        self.numberBox.addItem("")
        self.gridLayout.addWidget(self.numberBox, 2, 0, 1, 3)
        self.RUL = QtWidgets.QRadioButton(Lung_nodule_Dialog)
        self.RUL.setGeometry(QtCore.QRect(70, 40, 51, 91))
        self.RUL.setSizeIncrement(QtCore.QSize(20, 20))
        self.RUL.setAutoFillBackground(False)
        self.RUL.setText("")
        self.RUL.setIconSize(QtCore.QSize(50, 50))
        self.RUL.setObjectName("RUL")
        self.layoutWidget1 = QtWidgets.QWidget(Lung_nodule_Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(213, 270, 481, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.add_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)
        self.del_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.del_button.setObjectName("del_button")
        self.horizontalLayout.addWidget(self.del_button)
        self.unit = QtWidgets.QComboBox(self.layoutWidget1)
        self.unit.setObjectName("unit")
        self.unit.addItem("")
        self.unit.addItem("")
        self.horizontalLayout.addWidget(self.unit)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget1)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.label.raise_()
        self.treeWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.RUL.raise_()
        self.RML.raise_()
        self.RLL.raise_()
        self.LUL.raise_()
        self.LLL.raise_()

        self.retranslateUi(Lung_nodule_Dialog)
        self.buttonBox.accepted.connect(Lung_nodule_Dialog.accept)
        self.buttonBox.rejected.connect(Lung_nodule_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Lung_nodule_Dialog)
        Lung_nodule_Dialog.setTabOrder(self.RUL, self.RML)
        Lung_nodule_Dialog.setTabOrder(self.RML, self.RLL)
        Lung_nodule_Dialog.setTabOrder(self.RLL, self.LUL)
        Lung_nodule_Dialog.setTabOrder(self.LUL, self.LLL)
        Lung_nodule_Dialog.setTabOrder(self.LLL, self.segmentBox)
        Lung_nodule_Dialog.setTabOrder(self.segmentBox, self.numberBox)
        Lung_nodule_Dialog.setTabOrder(self.numberBox, self.lesionBox)
        Lung_nodule_Dialog.setTabOrder(self.lesionBox, self.uptake)
        Lung_nodule_Dialog.setTabOrder(self.uptake, self.size)
        Lung_nodule_Dialog.setTabOrder(self.size, self.position)
        Lung_nodule_Dialog.setTabOrder(self.position, self.maxSUV)
        Lung_nodule_Dialog.setTabOrder(self.maxSUV, self.treeWidget)
        Lung_nodule_Dialog.setTabOrder(self.treeWidget, self.checkBox)
        Lung_nodule_Dialog.setTabOrder(self.checkBox, self.add_button)
        Lung_nodule_Dialog.setTabOrder(self.add_button, self.del_button)
        Lung_nodule_Dialog.setTabOrder(self.del_button, self.unit)

    def retranslateUi(self, Lung_nodule_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Lung_nodule_Dialog.setWindowTitle(_translate("Lung_nodule_Dialog", "Dialog"))
        self.treeWidget.headerItem().setText(1, _translate("Lung_nodule_Dialog", "measure"))
        self.label_3.setText(_translate("Lung_nodule_Dialog", "IMA"))
        self.label_4.setText(_translate("Lung_nodule_Dialog", "maxSUV"))
        self.lesionBox.setItemText(0, _translate("Lung_nodule_Dialog", "nodule"))
        self.lesionBox.setItemText(1, _translate("Lung_nodule_Dialog", "tiny nodule"))
        self.lesionBox.setItemText(2, _translate("Lung_nodule_Dialog", "ground glass opacity lesion"))
        self.lesionBox.setItemText(3, _translate("Lung_nodule_Dialog", "GGO lesion"))
        self.lesionBox.setItemText(4, _translate("Lung_nodule_Dialog", "patch"))
        self.label_2.setText(_translate("Lung_nodule_Dialog", "Size"))
        self.uptake.setItemText(0, _translate("Lung_nodule_Dialog", "no"))
        self.uptake.setItemText(1, _translate("Lung_nodule_Dialog", "faint"))
        self.uptake.setItemText(2, _translate("Lung_nodule_Dialog", "mild increased"))
        self.uptake.setItemText(3, _translate("Lung_nodule_Dialog", "increased"))
        self.uptake.setItemText(4, _translate("Lung_nodule_Dialog", "intense"))
        self.numberBox.setItemText(0, _translate("Lung_nodule_Dialog", "a"))
        self.numberBox.setItemText(1, _translate("Lung_nodule_Dialog", "two"))
        self.numberBox.setItemText(2, _translate("Lung_nodule_Dialog", "tree"))
        self.numberBox.setItemText(3, _translate("Lung_nodule_Dialog", "several"))
        self.numberBox.setItemText(4, _translate("Lung_nodule_Dialog", "multiple"))
        self.numberBox.setItemText(5, _translate("Lung_nodule_Dialog", "widespread"))
        self.checkBox.setText(_translate("Lung_nodule_Dialog", "Full name"))
        self.add_button.setText(_translate("Lung_nodule_Dialog", "ADD"))
        self.del_button.setText(_translate("Lung_nodule_Dialog", "DEL"))
        self.unit.setItemText(0, _translate("Lung_nodule_Dialog", "cm"))
        self.unit.setItemText(1, _translate("Lung_nodule_Dialog", "mm"))

