# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'measurement.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_measurement(object):
    def setupUi(self, Dialog_measurement):
        Dialog_measurement.setObjectName("Dialog_measurement")
        Dialog_measurement.resize(321, 589)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        Dialog_measurement.setFont(font)
        self.gridLayout_7 = QtWidgets.QGridLayout(Dialog_measurement)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(Dialog_measurement)
        self.tabWidget.setObjectName("tabWidget")
        self.Simple = QtWidgets.QWidget()
        self.Simple.setObjectName("Simple")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Simple)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.Simple)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 1, 0, 1, 1)
        self.Simple_size_z = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Simple_size_z.setDecimals(2)
        self.Simple_size_z.setSingleStep(0.1)
        self.Simple_size_z.setObjectName("Simple_size_z")
        self.gridLayout_6.addWidget(self.Simple_size_z, 3, 1, 1, 1)
        self.Simple_size_y = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Simple_size_y.setKeyboardTracking(False)
        self.Simple_size_y.setDecimals(2)
        self.Simple_size_y.setSingleStep(0.1)
        self.Simple_size_y.setObjectName("Simple_size_y")
        self.gridLayout_6.addWidget(self.Simple_size_y, 2, 1, 1, 1)
        self.Simple_size_x = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.Simple_size_x.setDecimals(2)
        self.Simple_size_x.setSingleStep(0.1)
        self.Simple_size_x.setObjectName("Simple_size_x")
        self.gridLayout_6.addWidget(self.Simple_size_x, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_4 = QtWidgets.QGroupBox(self.Simple)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.Simple_uptake_maxSUV = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.Simple_uptake_maxSUV.setDecimals(1)
        self.Simple_uptake_maxSUV.setObjectName("Simple_uptake_maxSUV")
        self.gridLayout_4.addWidget(self.Simple_uptake_maxSUV, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.Simple)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 1)
        self.Simple_position_IMA = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.Simple_position_IMA.setDecimals(0)
        self.Simple_position_IMA.setMaximum(1000.0)
        self.Simple_position_IMA.setObjectName("Simple_position_IMA")
        self.gridLayout_5.addWidget(self.Simple_position_IMA, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 1, 0, 1, 1)
        self.Simple_position_image = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.Simple_position_image.setDecimals(0)
        self.Simple_position_image.setMaximum(1000.0)
        self.Simple_position_image.setObjectName("Simple_position_image")
        self.gridLayout_5.addWidget(self.Simple_position_image, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.Simple, "")
        self.Complex = QtWidgets.QWidget()
        self.Complex.setObjectName("Complex")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Complex)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.Complex)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.Complex_size_Length = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.Complex_size_Length.setDecimals(1)
        self.Complex_size_Length.setObjectName("Complex_size_Length")
        self.gridLayout.addWidget(self.Complex_size_Length, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.Complex_size_Width = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.Complex_size_Width.setDecimals(1)
        self.Complex_size_Width.setObjectName("Complex_size_Width")
        self.gridLayout.addWidget(self.Complex_size_Width, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.Complex_size_Height = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.Complex_size_Height.setDecimals(1)
        self.Complex_size_Height.setObjectName("Complex_size_Height")
        self.gridLayout.addWidget(self.Complex_size_Height, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.Complex_Volume_Vol = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.Complex_Volume_Vol.setDecimals(1)
        self.Complex_Volume_Vol.setObjectName("Complex_Volume_Vol")
        self.gridLayout.addWidget(self.Complex_Volume_Vol, 3, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Complex)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.Complex_uptake_maxSUV = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.Complex_uptake_maxSUV.setDecimals(1)
        self.Complex_uptake_maxSUV.setObjectName("Complex_uptake_maxSUV")
        self.gridLayout_2.addWidget(self.Complex_uptake_maxSUV, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.Complex_uptake_averageSUV = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.Complex_uptake_averageSUV.setDecimals(1)
        self.Complex_uptake_averageSUV.setObjectName("Complex_uptake_averageSUV")
        self.gridLayout_2.addWidget(self.Complex_uptake_averageSUV, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.Complex_uptake_TLG = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.Complex_uptake_TLG.setDecimals(1)
        self.Complex_uptake_TLG.setObjectName("Complex_uptake_TLG")
        self.gridLayout_2.addWidget(self.Complex_uptake_TLG, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.Complex_uptake_X = QtWidgets.QGroupBox(self.Complex)
        self.Complex_uptake_X.setObjectName("Complex_uptake_X")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Complex_uptake_X)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.Complex_uptake_X)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.Complex_position_IMA = QtWidgets.QDoubleSpinBox(self.Complex_uptake_X)
        self.Complex_position_IMA.setDecimals(0)
        self.Complex_position_IMA.setMaximum(600.0)
        self.Complex_position_IMA.setObjectName("Complex_position_IMA")
        self.gridLayout_3.addWidget(self.Complex_position_IMA, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.Complex_uptake_X)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.Complex_position_X = QtWidgets.QDoubleSpinBox(self.Complex_uptake_X)
        self.Complex_position_X.setDecimals(0)
        self.Complex_position_X.setMaximum(600.0)
        self.Complex_position_X.setObjectName("Complex_position_X")
        self.gridLayout_3.addWidget(self.Complex_position_X, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.Complex_uptake_X)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.Complex_position_Y = QtWidgets.QDoubleSpinBox(self.Complex_uptake_X)
        self.Complex_position_Y.setDecimals(0)
        self.Complex_position_Y.setMaximum(600.0)
        self.Complex_position_Y.setObjectName("Complex_position_Y")
        self.gridLayout_3.addWidget(self.Complex_position_Y, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.Complex_uptake_X)
        self.tabWidget.addTab(self.Complex, "")
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 3)
        self.cross_sign = QtWidgets.QComboBox(Dialog_measurement)
        self.cross_sign.setObjectName("cross_sign")
        self.cross_sign.addItem("")
        self.cross_sign.addItem("")
        self.gridLayout_7.addWidget(self.cross_sign, 1, 0, 1, 1)
        self.unit = QtWidgets.QComboBox(Dialog_measurement)
        self.unit.setObjectName("unit")
        self.unit.addItem("")
        self.unit.addItem("")
        self.gridLayout_7.addWidget(self.unit, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_measurement)
        self.buttonBox.setMinimumSize(QtCore.QSize(150, 0))
        self.buttonBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_7.addWidget(self.buttonBox, 1, 2, 1, 1)

        self.retranslateUi(Dialog_measurement)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog_measurement.accept)
        self.buttonBox.rejected.connect(Dialog_measurement.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_measurement)
        Dialog_measurement.setTabOrder(self.Simple_size_x, self.Simple_size_y)
        Dialog_measurement.setTabOrder(self.Simple_size_y, self.Simple_size_z)
        Dialog_measurement.setTabOrder(self.Simple_size_z, self.Simple_uptake_maxSUV)
        Dialog_measurement.setTabOrder(self.Simple_uptake_maxSUV, self.Simple_position_IMA)
        Dialog_measurement.setTabOrder(self.Simple_position_IMA, self.Simple_position_image)
        Dialog_measurement.setTabOrder(self.Simple_position_image, self.cross_sign)
        Dialog_measurement.setTabOrder(self.cross_sign, self.unit)
        Dialog_measurement.setTabOrder(self.unit, self.Complex_size_Length)
        Dialog_measurement.setTabOrder(self.Complex_size_Length, self.Complex_size_Width)
        Dialog_measurement.setTabOrder(self.Complex_size_Width, self.Complex_size_Height)
        Dialog_measurement.setTabOrder(self.Complex_size_Height, self.Complex_Volume_Vol)
        Dialog_measurement.setTabOrder(self.Complex_Volume_Vol, self.Complex_uptake_maxSUV)
        Dialog_measurement.setTabOrder(self.Complex_uptake_maxSUV, self.Complex_uptake_averageSUV)
        Dialog_measurement.setTabOrder(self.Complex_uptake_averageSUV, self.Complex_uptake_TLG)
        Dialog_measurement.setTabOrder(self.Complex_uptake_TLG, self.Complex_position_IMA)
        Dialog_measurement.setTabOrder(self.Complex_position_IMA, self.Complex_position_X)
        Dialog_measurement.setTabOrder(self.Complex_position_X, self.Complex_position_Y)
        Dialog_measurement.setTabOrder(self.Complex_position_Y, self.tabWidget)

    def retranslateUi(self, Dialog_measurement):
        _translate = QtCore.QCoreApplication.translate
        Dialog_measurement.setWindowTitle(_translate("Dialog_measurement", "Dialog"))
        self.groupBox_6.setTitle(_translate("Dialog_measurement", "Size"))
        self.label_19.setText(_translate("Dialog_measurement", "Height"))
        self.label_18.setText(_translate("Dialog_measurement", "Width"))
        self.label_17.setText(_translate("Dialog_measurement", "Length"))
        self.groupBox_4.setTitle(_translate("Dialog_measurement", "Tracer Uptake"))
        self.label_11.setText(_translate("Dialog_measurement", "maxSUV:"))
        self.groupBox_5.setTitle(_translate("Dialog_measurement", "Position"))
        self.label_14.setText(_translate("Dialog_measurement", "IMA:"))
        self.label_15.setText(_translate("Dialog_measurement", "image:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Simple), _translate("Dialog_measurement", "Simple"))
        self.groupBox.setTitle(_translate("Dialog_measurement", "Size"))
        self.label.setText(_translate("Dialog_measurement", "Length"))
        self.label_2.setText(_translate("Dialog_measurement", "Width"))
        self.label_3.setText(_translate("Dialog_measurement", "Height"))
        self.label_7.setText(_translate("Dialog_measurement", "Volume"))
        self.groupBox_2.setTitle(_translate("Dialog_measurement", "Tracer Uptake"))
        self.label_4.setText(_translate("Dialog_measurement", "maxSUV:"))
        self.label_5.setText(_translate("Dialog_measurement", "averageSUV:"))
        self.label_6.setText(_translate("Dialog_measurement", "TLG:"))
        self.Complex_uptake_X.setTitle(_translate("Dialog_measurement", "Position"))
        self.label_9.setText(_translate("Dialog_measurement", "IMA/image:"))
        self.label_10.setText(_translate("Dialog_measurement", "X:"))
        self.label_8.setText(_translate("Dialog_measurement", "Y:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Complex), _translate("Dialog_measurement", "Complex"))
        self.cross_sign.setItemText(0, _translate("Dialog_measurement", "x"))
        self.cross_sign.setItemText(1, _translate("Dialog_measurement", "*"))
        self.unit.setItemText(0, _translate("Dialog_measurement", "cm"))
        self.unit.setItemText(1, _translate("Dialog_measurement", "mm"))

