# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nmainUI.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 870)
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK TC Regular")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.pName = QtWidgets.QLineEdit(self.centralwidget)
        self.pName.setAcceptDrops(False)
        self.pName.setReadOnly(True)
        self.pName.setObjectName("pName")
        self.gridLayout.addWidget(self.pName, 0, 6, 1, 1)
        self.pID = QtWidgets.QLineEdit(self.centralwidget)
        self.pID.setObjectName("pID")
        self.gridLayout.addWidget(self.pID, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.search = QtWidgets.QPushButton(self.centralwidget)
        self.search.setObjectName("search")
        self.gridLayout.addWidget(self.search, 0, 4, 1, 1)
        self.saveOnly = QtWidgets.QPushButton(self.centralwidget)
        self.saveOnly.setObjectName("saveOnly")
        self.gridLayout.addWidget(self.saveOnly, 0, 8, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 5, 1, 1)
        self.saveClose = QtWidgets.QPushButton(self.centralwidget)
        self.saveClose.setObjectName("saveClose")
        self.gridLayout.addWidget(self.saveClose, 3, 2, 1, 1)
        self.patient_list = QtWidgets.QComboBox(self.centralwidget)
        self.patient_list.setObjectName("patient_list")
        self.gridLayout.addWidget(self.patient_list, 3, 6, 1, 1)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setObjectName("closeButton")
        self.gridLayout.addWidget(self.closeButton, 3, 8, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabEReport = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.tabEReport.setFont(font)
        self.tabEReport.setObjectName("tabEReport")
        self.nmtab = QtWidgets.QWidget()
        self.nmtab.setObjectName("nmtab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.nmtab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.nmreps = QtWidgets.QTreeWidget(self.nmtab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.nmreps.setFont(font)
        self.nmreps.setObjectName("nmreps")
        self.nmreps.headerItem().setText(0, "1")
        self.horizontalLayout_3.addWidget(self.nmreps)
        self.tabEReport.addTab(self.nmtab, "")
        self.pathtab = QtWidgets.QWidget()
        self.pathtab.setObjectName("pathtab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.pathtab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pathreps = QtWidgets.QTreeWidget(self.pathtab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.pathreps.setFont(font)
        self.pathreps.setObjectName("pathreps")
        self.pathreps.headerItem().setText(0, "1")
        self.horizontalLayout_4.addWidget(self.pathreps)
        self.tabEReport.addTab(self.pathtab, "")
        self.radiotab = QtWidgets.QWidget()
        self.radiotab.setObjectName("radiotab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.radiotab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radiorep = QtWidgets.QTreeWidget(self.radiotab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.radiorep.setFont(font)
        self.radiorep.setObjectName("radiorep")
        self.radiorep.headerItem().setText(0, "1")
        self.horizontalLayout_5.addWidget(self.radiorep)
        self.tabEReport.addTab(self.radiotab, "")
        self.scopytab = QtWidgets.QWidget()
        self.scopytab.setObjectName("scopytab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.scopytab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.scopyrep = QtWidgets.QTreeWidget(self.scopytab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.scopyrep.setFont(font)
        self.scopyrep.setObjectName("scopyrep")
        self.scopyrep.headerItem().setText(0, "1")
        self.horizontalLayout_6.addWidget(self.scopyrep)
        self.tabEReport.addTab(self.scopytab, "")
        self.others = QtWidgets.QWidget()
        self.others.setObjectName("others")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.others)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.othersrep = QtWidgets.QTreeWidget(self.others)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.othersrep.setFont(font)
        self.othersrep.setObjectName("othersrep")
        self.othersrep.headerItem().setText(0, "1")
        self.gridLayout_5.addWidget(self.othersrep, 0, 0, 1, 1)
        self.tabEReport.addTab(self.others, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.numrep = QtWidgets.QTreeWidget(self.tab)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.numrep.setFont(font)
        self.numrep.setObjectName("numrep")
        self.numrep.headerItem().setText(0, "1")
        self.gridLayout_2.addWidget(self.numrep, 0, 0, 1, 1)
        self.tabEReport.addTab(self.tab, "")
        self.horizontalLayout.addWidget(self.tabEReport)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.RBox = QtWidgets.QComboBox(self.centralwidget)
        self.RBox.setObjectName("RBox")
        self.horizontalLayout_2.addWidget(self.RBox)
        self.VBox = QtWidgets.QComboBox(self.centralwidget)
        self.VBox.setObjectName("VBox")
        self.horizontalLayout_2.addWidget(self.VBox)
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_2.addWidget(self.sendButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 21))
        self.menubar.setObjectName("menubar")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFont_Size = QtWidgets.QAction(MainWindow)
        self.actionFont_Size.setObjectName("actionFont_Size")
        self.actionFcolor = QtWidgets.QAction(MainWindow)
        self.actionFcolor.setObjectName("actionFcolor")
        self.actionBcolor = QtWidgets.QAction(MainWindow)
        self.actionBcolor.setObjectName("actionBcolor")
        self.menuSetting.addAction(self.actionFont_Size)
        self.menuSetting.addAction(self.actionFcolor)
        self.menuSetting.addAction(self.actionBcolor)
        self.menubar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(MainWindow)
        self.tabEReport.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "中文報告系統"))
        self.label.setText(_translate("MainWindow", "ID"))
        self.search.setText(_translate("MainWindow", "Search"))
        self.saveOnly.setText(_translate("MainWindow", "Save"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.saveClose.setText(_translate("MainWindow", "Save and Close"))
        self.closeButton.setText(_translate("MainWindow", "Close"))
        self.tabEReport.setTabText(self.tabEReport.indexOf(self.nmtab), _translate("MainWindow", "NM"))
        self.tabEReport.setTabText(self.tabEReport.indexOf(self.pathtab), _translate("MainWindow", "病理"))
        self.tabEReport.setTabText(self.tabEReport.indexOf(self.radiotab), _translate("MainWindow", "放射"))
        self.tabEReport.setTabText(self.tabEReport.indexOf(self.scopytab), _translate("MainWindow", "內視鏡"))
        self.tabEReport.setTabText(self.tabEReport.indexOf(self.others), _translate("MainWindow", "Others"))
        self.tabEReport.setTabText(self.tabEReport.indexOf(self.tab), _translate("MainWindow", "數據報告"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.actionFont_Size.setText(_translate("MainWindow", "Font Size"))
        self.actionFcolor.setText(_translate("MainWindow", "前景顏色"))
        self.actionBcolor.setText(_translate("MainWindow", "背景顏色"))

